chore: upgrade to ubuntu 26.04, fix builds
Seems to be a podman 6.0 brew configuration mismatch with the old
runners, let's just use the version in the new 26.04 runners.

```
Error: initializing destination docker://ghcr.io/bootcrew/ubuntu-bootc:latest-amd64: getting username and password: loading registries configuration "/etc/containers/registries.conf": registries.conf must be in v2 format but is in v1
```

bootc-dev/actions/bootc-ubuntu-setup currently relies on being run on
24.04